
# Build settings
# markdown: kramdown
# theme: minima

# this _config.yml be read from jekyll, solidjs
title: Jekyll Solidbase Theme
description: Solidbase Theme to Jekyll to use with GitHub Pages.
show_downloads: true
remote_theme: nikescar/jekyll-theme-solidbase
plugins:
  - jekyll-remote-theme

# Development server config, needed to load some of the content
#webrick:
#  headers:
#    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: Woojae, Park
repo_url: 'https://github.com/nikescar/jekyll-theme-solidbase'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
search_enabled: false
# logo: 'https://your.url/image.png'
# site_favicon: 'https://your.url/here.ico'
# theme: 'https://your.url/assets/css/theme.css'
# extra_theme: 'https://your.url/assets/css/theme_extra.css'
# The highlight.js library provides 79 different colours for their syntax highlighting. The default is github-gist.
hljs_style: github-gist
exclude: ['tmp']
