# configuration for vite.docs solidbase https://github.com/nikescar/jekyll-theme-solidbase
# Site settings
title: 치킨 만드는 법
description: 다양한 치킨 만드는 법 소개
show_downloads: true

# Excluded items can be re-enabled by adding them to the `include:` list.
exclude:
  - .github/

# Include in processing.
# The following items will be processed, even if they would otherwise be excluded.
include:
  - .well-known
  - docs
  - resources

# Theme settings
repo_url: 'https://github.com/nikescar/nikescar.github.io'
# site_url does not support subpaths, so it should be the root URL of your site.
site_url: 'https://nikescar.github.io'
# edit_on_github: true
# github_docs_folder: false
# sticky_navigation: true
# search_enabled: false
# logo: 'https://your.url/image.png'
site_favicon: './resources/favicon.ico'

theme_settings:
  social_links:
    GitHub: 'https://github.com/nikescar/nikescar.github.io'
  en:
    title: 치킨에 관한 모든것
    lang: en
    nav:
      문서: /docs
      리드미: /readme
      도움주신분: /credits
      # - Packages: /packages
      # - Blog: /blog
    sidebar:
      - 문서:
        - 가이드:
            "후라이드 치킨": /friedchicken
            "양념 치킨": /sweetchicken

