# configuration for vite.docs solidbase https://github.com/nikescar/ghaction-ghpage-solidbase-builder
# Site settings
title: 치킨 만드는 법
description: 다양한 치킨 만드는 법 소개
repo_url: 'https://github.com/nikescar/nikescar.github.io'
site_url: 'https://nikescar.github.io'
site_favicon: './resources/favicon.ico'

# 404 page redirection rules
404_subsite_urls:
  - /ghaction-ghpage-solidbase-builder/
  - /ghaction-ghpage-solid-ui-builder/
# Excluded items can be re-enabled by adding them to the `include:` list.
exclude:
  - .github/

# Include in processing.
# The following items will be processed, even if they would otherwise be excluded.
include:
  - .well-known
  - docs
  - resources
  - CREDITS.md
  - README.md

# Theme settings
theme_upstream: 'https://github.com/nikescar/ghaction-ghpage-solidbase-builder'
theme_settings:
  social_links:
    GitHub: 'https://github.com/nikescar/nikescar.github.io'
  en:
    title: 치킨에 관한 모든것
    lang: en
    nav:
      문서: /docs
      리드미: /readme
      도움주신분: /credits
      라이센스: https://github.com/nikescar/nikescar.github.io?tab=MIT-2-ov-file
    sidebar:
      - Docs:
        - 가이드:
            "후라이드 치킨": /friedchicken
            "양념 치킨": /sweetchicken

